name: br.com.armagedon.Practice
main: br.com.armagedon.br.com.armagedon.Practice
version: dev-1.0
author: Kinoques
description: br.com.armagedon.Practice Bukkit Plugin based on [game, game-bukkit, game-*]
website: www.armagedon.com.br
